# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'video_player_ui_vEHnbC.ui'
##
## Created by: Qt User Interface Compiler version 6.2.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
                            QMetaObject, QObject, QPoint, QRect,
                            QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
                           QFont, QFontDatabase, QGradient, QIcon,
                           QImage, QKeySequence, QLinearGradient, QPainter,
                           QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QMainWindow,
                               QPushButton, QSizePolicy, QSlider, QWidget)
import icons
import style_sheet


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(911, 721)
        MainWindow.setMinimumSize(QSize(911, 721))
        MainWindow.setMaximumSize(QSize(911, 721))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.trimMainFrame = QFrame(self.centralwidget)
        self.trimMainFrame.setObjectName(u"trimMainFrame")
        self.trimMainFrame.setGeometry(QRect(0, 0, 911, 721))
        self.trimMainFrame.setFocusPolicy(Qt.StrongFocus)
        self.trimMainFrame.setToolTipDuration(5)
        self.trimMainFrame.setStyleSheet(style_sheet.mainFrameSS)
        self.trimMainFrame.setFrameShape(QFrame.StyledPanel)
        self.trimMainFrame.setFrameShadow(QFrame.Raised)
        self.videoPlayerMainFrame = QFrame(self.trimMainFrame)
        self.videoPlayerMainFrame.setObjectName(u"videoPlayerMainFrame")
        self.videoPlayerMainFrame.setGeometry(QRect(10, 70, 871, 621))
        self.videoPlayerMainFrame.setStyleSheet(style_sheet.videoPlayerMainFrameSS)
        self.videoPlayerMainFrame.setFrameShape(QFrame.StyledPanel)
        self.videoPlayerMainFrame.setFrameShadow(QFrame.Raised)
        self.videoWidgetFrame = QFrame(self.videoPlayerMainFrame)
        self.videoWidgetFrame.setObjectName(u"videoWidgetFrame")
        self.videoWidgetFrame.setEnabled(True)
        self.videoWidgetFrame.setGeometry(QRect(20, 20, 831, 381))
        self.videoWidgetFrame.setStyleSheet(style_sheet.videoWidgetFrameSS)
        self.videoWidgetFrame.setFrameShape(QFrame.StyledPanel)
        self.videoWidgetFrame.setFrameShadow(QFrame.Raised)
        self.seekSliderFrame = QFrame(self.videoPlayerMainFrame)
        self.seekSliderFrame.setObjectName(u"seekSliderFrame")
        self.seekSliderFrame.setGeometry(QRect(0, 410, 871, 41))
        self.seekSliderFrame.setStyleSheet(style_sheet.seekSliderFrameSS)
        self.seekSliderFrame.setFrameShape(QFrame.StyledPanel)
        self.seekSliderFrame.setFrameShadow(QFrame.Raised)
        self.seekSlider = QSlider(self.seekSliderFrame)
        self.seekSlider.setObjectName(u"seekSlider")
        self.seekSlider.setGeometry(QRect(30, 0, 755, 22))
        self.seekSlider.setStyleSheet(style_sheet.seekSliderSS)
        self.seekSlider.setOrientation(Qt.Horizontal)
        self.seekSlider.setTickPosition(QSlider.NoTicks)
        self.seekSlider.setTickInterval(1)
        self.videoDurationLabel = QLabel(self.seekSliderFrame)
        self.videoDurationLabel.setObjectName(u"videoDurationLabel")
        self.videoDurationLabel.setGeometry(QRect(790, -1, 71, 21))
        self.videoDurationLabel.setStyleSheet(style_sheet.videoTimeLabelSS)
        self.trimControlFrame = QFrame(self.videoPlayerMainFrame)
        self.trimControlFrame.setObjectName(u"trimControlFrame")
        self.trimControlFrame.setGeometry(QRect(10, 440, 851, 101))
        self.trimControlFrame.setStyleSheet(style_sheet.trimControlFrameSS)
        self.trimControlFrame.setFrameShape(QFrame.StyledPanel)
        self.trimControlFrame.setFrameShadow(QFrame.Raised)
        self.playButton = QPushButton(self.trimControlFrame)
        self.playButton.setObjectName(u"playButton")
        self.playButton.setEnabled(False)
        self.playButton.setGeometry(QRect(55, 50, 41, 41))
        self.playButton.setStyleSheet(style_sheet.playButtonDisableSS)
        icon = QIcon()
        icon.addFile(u":/One/1486348532-music-play-pause-control-go-arrow_80458.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.playButton.setIcon(icon)
        self.playButton.setIconSize(QSize(45, 45))
        self.pauseButton = QPushButton(self.trimControlFrame)
        self.pauseButton.setObjectName(u"pauseButton")
        self.pauseButton.setGeometry(QRect(132, 50, 41, 41))
        self.pauseButton.setStyleSheet(style_sheet.pauseButtonEnableSS)
        icon1 = QIcon()
        icon1.addFile(u":/One/1486348534-music-pause-stop-control-play_80459.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.pauseButton.setIcon(icon1)
        self.pauseButton.setIconSize(QSize(45, 45))
        self.stopButton = QPushButton(self.trimControlFrame)
        self.stopButton.setObjectName(u"stopButton")
        self.stopButton.setGeometry(QRect(213, 50, 41, 41))
        self.stopButton.setStyleSheet(style_sheet.stopButtonEnableSS)
        icon2 = QIcon()
        icon2.addFile(u":/One/1486348535-music-square-stop-play-pause_80450.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.stopButton.setIcon(icon2)
        self.stopButton.setIconSize(QSize(45, 45))
        self.playerControlLabel = QLabel(self.trimControlFrame)
        self.playerControlLabel.setObjectName(u"playerControlLabel")
        self.playerControlLabel.setGeometry(QRect(32, 10, 241, 31))
        font = QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        self.playerControlLabel.setFont(font)
        self.playerControlLabel.setStyleSheet(style_sheet.playerControlLabelSS)
        self.playerControlLabel.setAlignment(Qt.AlignCenter)
        self.startTrimButton = QPushButton(self.trimControlFrame)
        self.startTrimButton.setObjectName(u"startTrimButton")
        self.startTrimButton.setGeometry(QRect(353, 57, 111, 31))
        self.startTrimButton.setStyleSheet(style_sheet.startEndTrimButtonSS)
        self.startTrimButton.setIconSize(QSize(50, 50))
        self.endTrimButton = QPushButton(self.trimControlFrame)
        self.endTrimButton.setObjectName(u"endTrimButton")
        self.endTrimButton.setGeometry(QRect(600, 57, 111, 31))
        self.endTrimButton.setStyleSheet(style_sheet.startEndTrimButtonSS)
        self.endTrimButton.setIconSize(QSize(50, 50))
        self.trimControlLabel = QLabel(self.trimControlFrame)
        self.trimControlLabel.setObjectName(u"trimControlLabel")
        self.trimControlLabel.setGeometry(QRect(329, 10, 491, 31))
        self.trimControlLabel.setFont(font)
        self.trimControlLabel.setStyleSheet(style_sheet.trimControlLabelSS)
        self.trimControlLabel.setAlignment(Qt.AlignCenter)
        self.startTrimLabel = QLabel(self.trimControlFrame)
        self.startTrimLabel.setObjectName(u"startTrimLabel")
        self.startTrimLabel.setGeometry(QRect(469, 57, 101, 31))
        self.startTrimLabel.setStyleSheet(style_sheet.startEndTrimLabelSS)
        self.endTrimLabel = QLabel(self.trimControlFrame)
        self.endTrimLabel.setObjectName(u"endTrimLabel")
        self.endTrimLabel.setGeometry(QRect(714, 57, 101, 31))
        self.endTrimLabel.setStyleSheet(style_sheet.startEndTrimLabelSS)
        self.confirmSettingsButton = QPushButton(self.videoPlayerMainFrame)
        self.confirmSettingsButton.setObjectName(u"confirmSettingsButton")
        self.confirmSettingsButton.setEnabled(True)
        self.confirmSettingsButton.setGeometry(QRect(110, 556, 145, 41))
        font1 = QFont()
        font1.setPointSize(13)
        font1.setBold(True)
        font1.setItalic(False)
        self.confirmSettingsButton.setFont(font1)
        self.confirmSettingsButton.setLayoutDirection(Qt.LeftToRight)
        self.confirmSettingsButton.setStyleSheet(style_sheet.allVideoPlayerPushButtonEnableSS)
        self.confirmSettingsButton.setAutoDefault(True)
        self.resetSettingsButton = QPushButton(self.videoPlayerMainFrame)
        self.resetSettingsButton.setObjectName(u"resetSettingsButton")
        self.resetSettingsButton.setEnabled(True)
        self.resetSettingsButton.setGeometry(QRect(357, 556, 145, 41))
        self.resetSettingsButton.setFont(font1)
        self.resetSettingsButton.setLayoutDirection(Qt.LeftToRight)
        self.resetSettingsButton.setStyleSheet(style_sheet.allVideoPlayerPushButtonEnableSS)
        self.resetSettingsButton.setAutoDefault(True)
        self.discardSettingsButton = QPushButton(self.videoPlayerMainFrame)
        self.discardSettingsButton.setObjectName(u"discardSettingsButton")
        self.discardSettingsButton.setEnabled(True)
        self.discardSettingsButton.setGeometry(QRect(600, 556, 145, 41))
        self.discardSettingsButton.setFont(font1)
        self.discardSettingsButton.setLayoutDirection(Qt.LeftToRight)
        self.discardSettingsButton.setStyleSheet(style_sheet.allVideoPlayerPushButtonEnableSS)
        self.discardSettingsButton.setAutoDefault(True)
        self.trimWindowLabel = QLabel(self.trimMainFrame)
        self.trimWindowLabel.setObjectName(u"trimWindowLabel")
        self.trimWindowLabel.setGeometry(QRect(210, -10, 471, 81))
        font2 = QFont()
        font2.setPointSize(43)
        font2.setBold(False)
        font2.setItalic(False)
        self.trimWindowLabel.setFont(font2)
        self.trimWindowLabel.setStyleSheet(style_sheet.trimWindowLabelSS)
        self.trimWindowLabel.setAlignment(Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)

    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Trim It", None))
        self.playButton.setText("")
        self.pauseButton.setText("")
        self.stopButton.setText("")
        self.playerControlLabel.setText(QCoreApplication.translate("MainWindow", u"Player Control", None))
        self.startTrimButton.setText(QCoreApplication.translate("MainWindow", u"Start Trim", None))
        self.endTrimButton.setText(QCoreApplication.translate("MainWindow", u"End Trim", None))
        self.trimControlLabel.setText(QCoreApplication.translate("MainWindow", u"Trim Control", None))
        self.startTrimLabel.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.endTrimLabel.setText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        # if QT_CONFIG(tooltip)
        self.confirmSettingsButton.setToolTip("")
        # endif // QT_CONFIG(tooltip)
        self.confirmSettingsButton.setText(QCoreApplication.translate("MainWindow", u"Confirm Settings", None))
        # if QT_CONFIG(tooltip)
        self.resetSettingsButton.setToolTip("")
        # endif // QT_CONFIG(tooltip)
        self.resetSettingsButton.setText(QCoreApplication.translate("MainWindow", u"Reset Settings", None))
        # if QT_CONFIG(tooltip)
        self.discardSettingsButton.setToolTip("")
        # endif // QT_CONFIG(tooltip)
        self.discardSettingsButton.setText(QCoreApplication.translate("MainWindow", u"Discard Settings", None))
        self.trimWindowLabel.setText(
            QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Trimming</p></body></html>", None))
    # retranslateUi
