# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'video_editor_ui_copyhjlEoI.ui'
##
## Created by: Qt User Interface Compiler version 6.2.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
                            QMetaObject, QObject, QPoint, QRect,
                            QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
                           QFont, QFontDatabase, QGradient, QIcon,
                           QImage, QKeySequence, QLinearGradient, QPainter,
                           QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QCheckBox, QComboBox,
                               QFrame, QLabel, QLineEdit, QMainWindow,
                               QPushButton, QRadioButton, QSizePolicy, QSpinBox,
                               QWidget)
import PySide6.QtGui as QtGui
import PySide6.QtCore as QtCore
import icons
import style_sheet


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1144, 830)
        MainWindow.setMinimumSize(QSize(1144, 830))
        MainWindow.setMaximumSize(QSize(1144, 830))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.mainFrame = QFrame(self.centralwidget)
        self.mainFrame.setObjectName(u"mainFrame")
        self.mainFrame.setGeometry(QRect(10, 10, 1131, 781))
        self.mainFrame.setFocusPolicy(Qt.StrongFocus)
        self.mainFrame.setToolTipDuration(5)
        self.mainFrame.setStyleSheet(style_sheet.mainFrameSS)
        self.mainFrame.setFrameShape(QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QFrame.Raised)
        self.selectVideoButton = QPushButton(self.mainFrame)
        self.selectVideoButton.setObjectName(u"selectVideoButton")
        self.selectVideoButton.setGeometry(QRect(150, 94, 141, 41))
        font = QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        self.selectVideoButton.setFont(font)
        self.selectVideoButton.setCursor(QCursor(Qt.ArrowCursor))
        self.selectVideoButton.setToolTipDuration(2)
        self.selectVideoButton.setStyleSheet(style_sheet.selectVideoButtonSS)
        self.selectVideoButton.setIconSize(QSize(20, 20))
        self.infoFrame = QFrame(self.mainFrame)
        self.infoFrame.setObjectName(u"infoFrame")
        self.infoFrame.setGeometry(QRect(20, 250, 411, 491))
        self.infoFrame.setStyleSheet(style_sheet.infoFrameSS)
        self.infoFrame.setFrameShape(QFrame.StyledPanel)
        self.infoFrame.setFrameShadow(QFrame.Raised)
        self.thumnailFrame = QFrame(self.infoFrame)
        self.thumnailFrame.setObjectName(u"thumnailFrame")
        self.thumnailFrame.setEnabled(True)
        self.thumnailFrame.setGeometry(QRect(8, 160, 190, 130))
        self.thumnailFrame.setStyleSheet(style_sheet.thumnailFrameSS)
        self.thumnailFrame.setFrameShape(QFrame.StyledPanel)
        self.thumnailFrame.setFrameShadow(QFrame.Raised)
        self.infothumbnaiLabel = QLabel(self.thumnailFrame)
        self.infothumbnaiLabel.setObjectName(u"infothumbnaiLabel")
        self.infothumbnaiLabel.setGeometry(QRect(0, 0, 190, 130))
        self.infothumbnaiLabel.setPixmap(QPixmap(u":/One/applicationimagepng_103490.png"))
        self.infothumbnaiLabel.setScaledContents(True)
        self.infothumbnaiLabel.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.infoplayVideoButton = QPushButton(self.infoFrame)
        self.infoplayVideoButton.setObjectName(u"infoplayVideoButton")
        self.infoplayVideoButton.setEnabled(False)
        self.infoplayVideoButton.setGeometry(QRect(80, 310, 51, 51))
        font1 = QFont()
        font1.setPointSize(11)
        font1.setBold(True)
        self.infoplayVideoButton.setFont(font1)
        self.infoplayVideoButton.setStyleSheet(style_sheet.infoplayVideoButtonDisableSS)
        icon = QIcon()
        icon.addFile(u":/One/play-button_icon-icons.com_53922.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.infoplayVideoButton.setIcon(icon)
        self.infoplayVideoButton.setIconSize(QSize(40, 45))
        self.infoNameLabel2 = QLabel(self.infoFrame)
        self.infoNameLabel2.setObjectName(u"infoNameLabel2")
        self.infoNameLabel2.setEnabled(True)

        self.infoNameLabel2.setGeometry(QRect(90, 70, 300, 31))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        font2.setItalic(False)
        self.infoNameLabel2.setFont(font2)
        self.infoNameLabel2.setStyleSheet(style_sheet.infoAllLabel2DisableSS)
        self.infoNameLabel2.setAlignment(Qt.AlignCenter)
        self.infoNameLabel = QLabel(self.infoFrame)
        self.infoNameLabel.setObjectName(u"infoNameLabel")
        self.infoNameLabel.setGeometry(QRect(10, 70, 81, 31))
        self.infoNameLabel.setFont(font)
        self.infoNameLabel.setStyleSheet(style_sheet.infoAllLabel1SS)
        self.infoNameLabel.setAlignment(Qt.AlignLeft)
        self.infoLenghLabel2 = QLabel(self.infoFrame)
        self.infoLenghLabel2.setObjectName(u"infoLenghLabel2")
        self.infoLenghLabel2.setEnabled(True)
        self.infoLenghLabel2.setGeometry(QRect(265, 180, 161, 31))
        self.infoLenghLabel2.setFont(font2)
        self.infoLenghLabel2.setStyleSheet(style_sheet.infoAllLabel2DisableSS)
        self.infoLenghLabel2.setAlignment(Qt.AlignCenter)
        self.infoLenghLabel = QLabel(self.infoFrame)
        self.infoLenghLabel.setObjectName(u"infoLenghLabel")
        self.infoLenghLabel.setGeometry(QRect(220, 180, 81, 31))
        self.infoLenghLabel.setFont(font)
        self.infoLenghLabel.setStyleSheet(style_sheet.infoAllLabel1SS)
        self.infoLenghLabel.setAlignment(Qt.AlignCenter)
        self.infoBitrateLabel2 = QLabel(self.infoFrame)
        self.infoBitrateLabel2.setObjectName(u"infoBitrateLabel2")
        self.infoBitrateLabel2.setEnabled(True)
        self.infoBitrateLabel2.setGeometry(QRect(265, 230, 161, 31))
        self.infoBitrateLabel2.setFont(font2)
        self.infoBitrateLabel2.setStyleSheet(style_sheet.infoAllLabel2DisableSS)
        self.infoBitrateLabel2.setAlignment(Qt.AlignCenter)
        self.infoBitrateLabel = QLabel(self.infoFrame)
        self.infoBitrateLabel.setObjectName(u"infoBitrateLabel")
        self.infoBitrateLabel.setGeometry(QRect(220, 230, 81, 31))
        self.infoBitrateLabel.setFont(font)
        self.infoBitrateLabel.setStyleSheet(style_sheet.infoAllLabel1SS)
        self.infoBitrateLabel.setAlignment(Qt.AlignCenter)
        self.infoFpsLabel2 = QLabel(self.infoFrame)
        self.infoFpsLabel2.setObjectName(u"infoFpsLabel2")
        self.infoFpsLabel2.setEnabled(True)
        self.infoFpsLabel2.setGeometry(QRect(265, 280, 161, 31))
        self.infoFpsLabel2.setFont(font2)
        self.infoFpsLabel2.setStyleSheet(style_sheet.infoAllLabel2DisableSS)
        self.infoFpsLabel2.setAlignment(Qt.AlignCenter)
        self.infoFpsLabel = QLabel(self.infoFrame)
        self.infoFpsLabel.setObjectName(u"infoFpsLabel")
        self.infoFpsLabel.setGeometry(QRect(220, 280, 81, 31))
        self.infoFpsLabel.setFont(font)
        self.infoFpsLabel.setStyleSheet(style_sheet.infoAllLabel1SS)
        self.infoFpsLabel.setAlignment(Qt.AlignCenter)
        self.infoResolutionLabel2 = QLabel(self.infoFrame)
        self.infoResolutionLabel2.setObjectName(u"infoResolutionLabel2")
        self.infoResolutionLabel2.setEnabled(True)
        self.infoResolutionLabel2.setGeometry(QRect(265, 330, 161, 31))
        self.infoResolutionLabel2.setFont(font2)
        self.infoResolutionLabel2.setStyleSheet(style_sheet.infoAllLabel2DisableSS)
        self.infoResolutionLabel2.setAlignment(Qt.AlignCenter)
        self.infoResolutionLabel = QLabel(self.infoFrame)
        self.infoResolutionLabel.setObjectName(u"infoResolutionLabel")
        self.infoResolutionLabel.setGeometry(QRect(180, 330, 121, 31))
        self.infoResolutionLabel.setFont(font)
        self.infoResolutionLabel.setStyleSheet(style_sheet.infoAllLabel1SS)
        self.infoResolutionLabel.setAlignment(Qt.AlignCenter)
        self.videoInformationLabel = QLabel(self.infoFrame)
        self.videoInformationLabel.setObjectName(u"videoInformationLabel")
        self.videoInformationLabel.setGeometry(QRect(10, 10, 393, 41))
        font3 = QFont()
        font3.setPointSize(17)
        font3.setBold(True)
        font3.setItalic(False)
        self.videoInformationLabel.setFont(font3)
        self.videoInformationLabel.setStyleSheet(style_sheet.videoInformationLabelSS)
        self.videoInformationLabel.setAlignment(Qt.AlignCenter)
        self.infoSizeLabel2 = QLabel(self.infoFrame)
        self.infoSizeLabel2.setObjectName(u"infoSizeLabel2")
        self.infoSizeLabel2.setEnabled(True)
        self.infoSizeLabel2.setGeometry(QRect(265, 130, 161, 31))
        self.infoSizeLabel2.setFont(font2)
        self.infoSizeLabel2.setStyleSheet(style_sheet.infoAllLabel2DisableSS)
        self.infoSizeLabel2.setAlignment(Qt.AlignCenter)
        self.infoSizeLabel = QLabel(self.infoFrame)
        self.infoSizeLabel.setObjectName(u"infoSizeLabel")
        self.infoSizeLabel.setGeometry(QRect(220, 130, 81, 31))
        self.infoSizeLabel.setFont(font)
        self.infoSizeLabel.setStyleSheet(style_sheet.infoAllLabel1SS)
        self.infoSizeLabel.setAlignment(Qt.AlignCenter)
        self.logoLabel = QLabel(self.infoFrame)
        self.logoLabel.setObjectName(u"logoLabel")
        self.logoLabel.setGeometry(QRect(125, 400, 190, 60))
        self.logoLabel.setStyleSheet(style_sheet.logoLableSS)
        self.logoLabel.setPixmap(QPixmap(u":/One/Ubisoft_Pune_HORIZONTAL_LOGO_WHITE.png"))
        self.logoLabel.setScaledContents(True)
        self.convertFrame = QFrame(self.mainFrame)
        self.convertFrame.setObjectName(u"convertFrame")
        self.convertFrame.setGeometry(QRect(440, 100, 671, 641))
        self.convertFrame.setStyleSheet(style_sheet.convertFrameSS)
        self.convertFrame.setFrameShape(QFrame.StyledPanel)
        self.convertFrame.setFrameShadow(QFrame.Raised)
        self.outputFormatFrame = QFrame(self.convertFrame)
        self.outputFormatFrame.setObjectName(u"outputFormatFrame")
        self.outputFormatFrame.setEnabled(True)
        self.outputFormatFrame.setGeometry(QRect(0, 460, 671, 111))
        self.outputFormatFrame.setStyleSheet(style_sheet.outputFormatFrameSS)
        self.outputFormatFrame.setFrameShape(QFrame.StyledPanel)
        self.outputFormatFrame.setFrameShadow(QFrame.Raised)
        self.mp4RadioButton = QRadioButton(self.outputFormatFrame)
        self.mp4RadioButton.setObjectName(u"mp4RadioButton")
        self.mp4RadioButton.setEnabled(False)
        self.mp4RadioButton.setGeometry(QRect(70, 40, 101, 71))
        self.mp4RadioButton.setFont(font1)
        self.mp4RadioButton.setStyleSheet(style_sheet.outputFormatAllRadioButtonSS)
        icon1 = QIcon()
        icon1.addFile(u":/One/mp4 file.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.mp4RadioButton.setIcon(icon1)
        self.mp4RadioButton.setIconSize(QSize(80, 80))
        self.aviRadioButton = QRadioButton(self.outputFormatFrame)
        self.aviRadioButton.setObjectName(u"aviRadioButton")
        self.aviRadioButton.setEnabled(False)
        self.aviRadioButton.setGeometry(QRect(280, 40, 101, 71))
        self.aviRadioButton.setFont(font1)
        self.aviRadioButton.setStyleSheet(style_sheet.outputFormatAllRadioButtonSS)
        icon2 = QIcon()
        icon2.addFile(u":/One/avi file.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.aviRadioButton.setIcon(icon2)
        self.aviRadioButton.setIconSize(QSize(80, 80))
        self.aviRadioButton.setCheckable(True)
        self.wmvRadioButton = QRadioButton(self.outputFormatFrame)
        self.wmvRadioButton.setObjectName(u"wmvRadioButton")
        self.wmvRadioButton.setEnabled(False)
        self.wmvRadioButton.setGeometry(QRect(500, 40, 101, 71))
        font4 = QFont()
        font4.setPointSize(10)
        font4.setBold(True)
        self.wmvRadioButton.setFont(font4)
        self.wmvRadioButton.setStyleSheet(style_sheet.outputFormatAllRadioButtonSS)
        icon3 = QIcon()
        icon3.addFile(u":/One/wmv file.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.wmvRadioButton.setIcon(icon3)
        self.wmvRadioButton.setIconSize(QSize(80, 80))
        self.outputFormatLabel = QLabel(self.outputFormatFrame)
        self.outputFormatLabel.setObjectName(u"outputFormatLabel")
        self.outputFormatLabel.setGeometry(QRect(10, 10, 651, 31))
        font5 = QFont()
        font5.setPointSize(14)
        font5.setBold(True)
        font5.setItalic(False)
        self.outputFormatLabel.setFont(font5)
        self.outputFormatLabel.setStyleSheet(style_sheet.outputFormatLabelSS)
        self.outputFormatLabel.setAlignment(Qt.AlignCenter)
        self.outputSettingFrame = QFrame(self.convertFrame)
        self.outputSettingFrame.setObjectName(u"outputSettingFrame")
        self.outputSettingFrame.setEnabled(True)
        self.outputSettingFrame.setGeometry(QRect(0, 210, 671, 251))
        self.outputSettingFrame.setStyleSheet(style_sheet.outputSettingFrameSS)
        self.outputSettingFrame.setFrameShape(QFrame.StyledPanel)
        self.outputSettingFrame.setFrameShadow(QFrame.Sunken)
        self.bitrateReductionLabel = QLabel(self.outputSettingFrame)
        self.bitrateReductionLabel.setObjectName(u"bitrateReductionLabel")
        self.bitrateReductionLabel.setGeometry(QRect(30, 70, 181, 31))
        self.bitrateReductionLabel.setFont(font)
        self.bitrateReductionLabel.setStyleSheet(style_sheet.infoAllLabel1SS)
        self.bitrateReductionLabel.setAlignment(Qt.AlignCenter)
        self.fpsLabel = QLabel(self.outputSettingFrame)
        self.fpsLabel.setObjectName(u"fpsLabel")
        self.fpsLabel.setGeometry(QRect(60, 130, 131, 31))
        self.fpsLabel.setFont(font)
        self.fpsLabel.setStyleSheet(style_sheet.infoAllLabel1SS)
        self.fpsLabel.setAlignment(Qt.AlignCenter)
        self.resolutionLabel = QLabel(self.outputSettingFrame)
        self.resolutionLabel.setObjectName(u"resolutionLabel")
        self.resolutionLabel.setGeometry(QRect(60, 190, 131, 31))
        self.resolutionLabel.setFont(font)
        self.resolutionLabel.setStyleSheet(style_sheet.infoAllLabel1SS)
        self.resolutionLabel.setAlignment(Qt.AlignCenter)
        self.outputSettingsLabel = QLabel(self.outputSettingFrame)
        self.outputSettingsLabel.setObjectName(u"outputSettingsLabel")
        self.outputSettingsLabel.setGeometry(QRect(10, 10, 651, 31))
        self.outputSettingsLabel.setFont(font5)
        self.outputSettingsLabel.setStyleSheet(style_sheet.outputSettingsLabelSS)
        self.outputSettingsLabel.setAlignment(Qt.AlignCenter)
        self.targetSizeFrame = QFrame(self.outputSettingFrame)
        self.targetSizeFrame.setObjectName(u"targetSizeFrame")
        self.targetSizeFrame.setGeometry(QRect(460, 150, 191, 81))
        self.targetSizeFrame.setStyleSheet(style_sheet.targetSizeFrameSS)
        self.targetSizeFrame.setFrameShape(QFrame.StyledPanel)
        self.targetSizeFrame.setFrameShadow(QFrame.Raised)
        self.provideSizeLineEdit = QLineEdit(self.targetSizeFrame)
        self.provideSizeLineEditRegexp = QtCore.QRegularExpression("\d{3}|\d{2}|\d{1}")
        self.provideSizeLineEditValidator = QtGui.QRegularExpressionValidator(self.provideSizeLineEditRegexp)
        self.provideSizeLineEdit.setValidator(self.provideSizeLineEditValidator)
        self.provideSizeLineEdit.setObjectName(u"provideSizeLineEdit")
        self.provideSizeLineEdit.setEnabled(False)
        self.provideSizeLineEdit.setGeometry(QRect(40, 40, 117, 31))
        font6 = QFont()
        font6.setPointSize(9)
        font6.setBold(False)
        font6.setItalic(False)
        self.provideSizeLineEdit.setFont(font6)
        self.provideSizeLineEdit.setFocusPolicy(Qt.ClickFocus)
        self.provideSizeLineEdit.setStyleSheet(style_sheet.provideSizeLineEditDisableSS)
        self.provideSizeLineEdit.setAlignment(Qt.AlignCenter)
        self.provideSizeLineEdit.setClearButtonEnabled(False)
        self.targetSizeLabel = QLabel(self.targetSizeFrame)
        self.targetSizeLabel.setObjectName(u"targetSizeLabel")
        self.targetSizeLabel.setEnabled(True)
        self.targetSizeLabel.setGeometry(QRect(30, 10, 151, 21))
        self.targetSizeLabel.setFont(font)
        self.targetSizeLabel.setStyleSheet(style_sheet.targetSizeLabelSS)
        self.keepAudioFrame = QFrame(self.outputSettingFrame)
        self.keepAudioFrame.setObjectName(u"keepAudioFrame")
        self.keepAudioFrame.setGeometry(QRect(480, 70, 151, 61))
        self.keepAudioFrame.setStyleSheet(style_sheet.keepAudioFrameSS)
        self.keepAudioFrame.setFrameShape(QFrame.StyledPanel)
        self.keepAudioFrame.setFrameShadow(QFrame.Raised)
        self.keepAudioCheckBox = QCheckBox(self.keepAudioFrame)
        self.keepAudioCheckBox.setObjectName(u"keepAudioCheckBox")
        self.keepAudioCheckBox.setEnabled(False)
        self.keepAudioCheckBox.setGeometry(QRect(10, 10, 131, 41))
        self.keepAudioCheckBox.setBaseSize(QSize(0, 0))
        self.keepAudioCheckBox.setFont(font)
        self.keepAudioCheckBox.setStyleSheet(style_sheet.keepAudioCheckBoxDisableSS)
        self.keepAudioCheckBox.setChecked(True)
        self.fpsSpinBox = QSpinBox(self.outputSettingFrame)
        self.fpsSpinBox.setObjectName(u"fpsSpinBox")
        self.fpsSpinBox.setSpecialValueText("Unset")
        self.fpsSpinBox.setEnabled(False)
        self.fpsSpinBox.setGeometry(QRect(230, 130, 181, 31))
        font7 = QFont()
        font7.setPointSize(9)
        font7.setBold(True)
        self.fpsSpinBox.setFont(font7)
        self.fpsSpinBox.setStyleSheet(style_sheet.bitrateReductionFpsSpinBoxDisableSS)
        self.fpsSpinBox.setAlignment(Qt.AlignCenter)
        self.fpsSpinBox.setMinimum(22)
        self.fpsSpinBox.setMaximum(60)
        self.fpsSpinBox.setSingleStep(1)
        self.fpsSpinBox.setStepType(QAbstractSpinBox.DefaultStepType)
        self.fpsSpinBox.setValue(22)
        self.bitrateReductionSpinBox = QSpinBox(self.outputSettingFrame)
        self.bitrateReductionSpinBox.setObjectName(u"bitrateReductionSpinBox")
        self.bitrateReductionSpinBox.setSpecialValueText("Unset")
        self.bitrateReductionSpinBox.setEnabled(False)
        self.bitrateReductionSpinBox.setGeometry(QRect(230, 70, 181, 31))
        self.bitrateReductionSpinBox.setFont(font7)
        self.bitrateReductionSpinBox.setStyleSheet(style_sheet.bitrateReductionFpsSpinBoxDisableSS)
        self.bitrateReductionSpinBox.setAlignment(Qt.AlignCenter)
        self.bitrateReductionSpinBox.setMinimum(5)
        self.bitrateReductionSpinBox.setMaximum(40)
        self.bitrateReductionSpinBox.setSingleStep(5)
        self.bitrateReductionSpinBox.setStepType(QAbstractSpinBox.DefaultStepType)
        self.bitrateReductionSpinBox.setValue(5)
        self.bitrateReductionPercentLabel = QLabel(self.outputSettingFrame)
        self.bitrateReductionPercentLabel.setObjectName(u"bitrateReductionPercentLabel")
        self.bitrateReductionPercentLabel.setGeometry(QRect(420, 70, 31, 31))
        self.bitrateReductionPercentLabel.setStyleSheet(style_sheet.bitrateReductionPercentLabelSS)
        self.resolutionComboBoxFrame = QFrame(self.outputSettingFrame)
        self.resolutionComboBoxFrame.setObjectName(u"resolutionComboBoxFrame")
        self.resolutionComboBoxFrame.setGeometry(QRect(230, 190, 181, 31))
        self.resolutionComboBoxFrame.setStyleSheet(style_sheet.resolutionComboBoxFrameSS)
        self.resolutionComboBoxFrame.setStyleSheet(style_sheet.resolutionComboBoxFrameSS)
        self.resolutionComboBoxFrame.setFrameShape(QFrame.StyledPanel)
        self.resolutionComboBoxFrame.setFrameShadow(QFrame.Raised)
        self.resolutionComboBox = QComboBox(self.resolutionComboBoxFrame)
        self.resolutionComboBox.addItem("")
        self.resolutionComboBox.addItem("")
        self.resolutionComboBox.addItem("")
        self.resolutionComboBox.addItem("")
        self.resolutionComboBox.setObjectName(u"resolutionComboBox")
        self.resolutionComboBox.setEnabled(False)
        self.resolutionComboBox.setGeometry(QRect(0, 0, 181, 31))
        font8 = QFont()
        font8.setBold(True)
        self.resolutionComboBox.setFont(font8)
        self.resolutionComboBox.setStyleSheet(style_sheet.resolutionComboBoxDisableSS)
        self.resolutionComboBox.setFrame(False)
        self.targetSizeFrame.raise_()
        self.keepAudioFrame.raise_()
        self.bitrateReductionLabel.raise_()
        self.fpsLabel.raise_()
        self.resolutionLabel.raise_()
        self.outputSettingsLabel.raise_()
        self.fpsSpinBox.raise_()
        self.bitrateReductionSpinBox.raise_()
        self.bitrateReductionPercentLabel.raise_()
        self.resolutionComboBoxFrame.raise_()
        self.trimSettingFrame = QFrame(self.convertFrame)
        self.trimSettingFrame.setObjectName(u"trimSettingFrame")
        self.trimSettingFrame.setGeometry(QRect(0, 60, 671, 151))
        self.trimSettingFrame.setStyleSheet(style_sheet.trimSettingFrameSS)
        self.trimSettingFrame.setFrameShape(QFrame.StyledPanel)
        self.trimSettingFrame.setFrameShadow(QFrame.Raised)
        self.trimVideoButton = QPushButton(self.trimSettingFrame)
        self.trimVideoButton.setObjectName(u"trimVideoButton")
        self.trimVideoButton.setEnabled(False)
        self.trimVideoButton.setGeometry(QRect(475, 70, 150, 41))
        self.trimVideoButton.setFont(font)
        self.trimVideoButton.setStyleSheet(style_sheet.allPushButtonDisableSS)
        self.trimVideoButton.setIconSize(QSize(30, 30))
        self.startTimeLabel = QLabel(self.trimSettingFrame)
        self.startTimeLabel.setObjectName(u"startTimeLabel")
        self.startTimeLabel.setGeometry(QRect(50, 60, 151, 31))
        self.startTimeLabel.setFont(font)
        self.startTimeLabel.setStyleSheet(style_sheet.infoAllLabel1SS)
        self.startTimeLabel.setAlignment(Qt.AlignCenter)
        self.endTimeLabel = QLabel(self.trimSettingFrame)
        self.endTimeLabel.setObjectName(u"endTimeLabel")
        self.endTimeLabel.setGeometry(QRect(50, 100, 151, 31))
        self.endTimeLabel.setFont(font)
        self.endTimeLabel.setStyleSheet(style_sheet.infoAllLabel1SS)
        self.endTimeLabel.setAlignment(Qt.AlignCenter)
        self.startTimeLineEdit = QLineEdit(self.trimSettingFrame)
        self.startTimeLineEdit.setObjectName(u"startTimeLineEdit")
        self.startTimeLineEdit.setReadOnly(True)
        # self.startTimeLineEditRegexp = QtCore.QRegularExpression(r"\d{2}:\d{2}+:\d{2}")
        # self.startTimeLineEditValidator = QtGui.QRegularExpressionValidator(self.startTimeLineEditRegexp)
        # self.startTimeLineEdit.setValidator(self.startTimeLineEditValidator)
        self.startTimeLineEdit.setGeometry(QRect(230, 60, 181, 31))
        font9 = QFont()
        font9.setPointSize(11)
        font9.setBold(True)
        font9.setItalic(False)
        self.startTimeLineEdit.setFont(font9)
        self.startTimeLineEdit.setEnabled(False)
        self.startTimeLineEdit.setStyleSheet(style_sheet.startEndTimeLineEditDisableSS)
        self.startTimeLineEdit.setAlignment(Qt.AlignCenter)
        self.endTimeLineEdit = QLineEdit(self.trimSettingFrame)
        self.endTimeLineEdit.setObjectName(u"endTimeLineEdit")
        self.endTimeLineEdit.setReadOnly(True)
        # self.endTimeLineEditRegexp = QtCore.QRegularExpression(r"\d{2}:\d{2}+:\d{2}")
        # self.endTimeLineEditValidator = QtGui.QRegularExpressionValidator(self.endTimeLineEditRegexp)
        # self.endTimeLineEdit.setValidator(self.endTimeLineEditValidator)
        self.endTimeLineEdit.setGeometry(QRect(230, 100, 181, 31))
        self.endTimeLineEdit.setFont(font9)
        self.endTimeLineEdit.setEnabled(False)
        self.endTimeLineEdit.setStyleSheet(style_sheet.startEndTimeLineEditDisableSS)
        self.endTimeLineEdit.setAlignment(Qt.AlignCenter)
        self.trimSettingsLabel = QLabel(self.trimSettingFrame)
        self.trimSettingsLabel.setObjectName(u"trimSettingsLabel")
        self.trimSettingsLabel.setGeometry(QRect(10, 10, 651, 31))
        self.trimSettingsLabel.setFont(font5)
        self.trimSettingsLabel.setStyleSheet(style_sheet.trimSettingsLabelSS)
        self.trimSettingsLabel.setAlignment(Qt.AlignCenter)
        self.convertVideoButton = QPushButton(self.convertFrame)
        self.convertVideoButton.setObjectName(u"convertVideoButton")
        self.convertVideoButton.setEnabled(False)
        self.convertVideoButton.setGeometry(QRect(470, 585, 141, 41))
        self.convertVideoButton.setFont(font)
        self.convertVideoButton.setLayoutDirection(Qt.LeftToRight)
        self.convertVideoButton.setStyleSheet(style_sheet.allPushButtonDisableSS)
        self.convertVideoButton.setAutoDefault(True)
        self.conversionSettingsLabel = QLabel(self.convertFrame)
        self.conversionSettingsLabel.setObjectName(u"conversionSettingsLabel")
        self.conversionSettingsLabel.setGeometry(QRect(10, 10, 652, 41))
        self.conversionSettingsLabel.setFont(font3)
        self.conversionSettingsLabel.setStyleSheet(style_sheet.conversionSettingsLabelSS)
        self.conversionSettingsLabel.setAlignment(Qt.AlignCenter)
        self.loadConfigButton = QPushButton(self.convertFrame)
        self.loadConfigButton.setObjectName(u"loadConfigButton")
        self.loadConfigButton.setEnabled(False)
        self.loadConfigButton.setGeometry(QRect(270, 585, 141, 41))
        self.loadConfigButton.setFont(font)
        self.loadConfigButton.setLayoutDirection(Qt.LeftToRight)
        self.loadConfigButton.setStyleSheet(style_sheet.allPushButtonDisableSS)
        self.loadConfigButton.setAutoDefault(True)
        self.saveConfigButton = QPushButton(self.convertFrame)
        self.saveConfigButton.setObjectName(u"saveConfigButton")
        self.saveConfigButton.setEnabled(False)
        self.saveConfigButton.setGeometry(QRect(70, 585, 141, 41))
        self.saveConfigButton.setFont(font)
        self.saveConfigButton.setLayoutDirection(Qt.LeftToRight)
        self.saveConfigButton.setStyleSheet(style_sheet.allPushButtonDisableSS)
        self.saveConfigButton.setAutoDefault(True)
        self.trimSettingFrame.raise_()
        self.outputSettingFrame.raise_()
        self.outputFormatFrame.raise_()
        self.convertVideoButton.raise_()
        self.conversionSettingsLabel.raise_()
        self.loadConfigButton.raise_()
        self.saveConfigButton.raise_()
        self.stripFrame = QFrame(self.mainFrame)
        self.stripFrame.setObjectName(u"stripFrame")
        self.stripFrame.setGeometry(QRect(0, 1, 1131, 71))
        self.stripFrame.setStyleSheet(u"background-color: rgb(14, 47, 75)")
        self.stripFrame.setFrameShape(QFrame.StyledPanel)
        self.stripFrame.setFrameShadow(QFrame.Raised)
        self.titleLabel = QLabel(self.mainFrame)
        self.titleLabel.setObjectName(u"titleLabel")
        self.titleLabel.setGeometry(QRect(-130, -5, 471, 81))
        font10 = QFont()
        font10.setPointSize(43)
        font10.setBold(False)
        font10.setItalic(False)
        self.titleLabel.setFont(font10)
        self.titleLabel.setStyleSheet(style_sheet.titleLabelSS)
        self.titleLabel.setAlignment(Qt.AlignCenter)
        self.closeButton = QPushButton(self.mainFrame)
        self.closeButton.setObjectName(u"closeButton")
        self.closeButton.setGeometry(QRect(1050, 11, 49, 49))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(255, 21, 52, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        # if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush)
        # endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        # if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush)
        # endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        # if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush)
        # endif
        self.closeButton.setPalette(palette)
        font11 = QFont()
        font11.setPointSize(23)
        font11.setBold(True)
        self.closeButton.setFont(font11)
        self.closeButton.setStyleSheet(style_sheet.closeButtonSS)
        icon4 = QIcon()
        icon4.addFile(u":/One/close.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.closeButton.setIcon(icon4)
        self.closeButton.setIconSize(QSize(43, 43))
        self.closeButton.setAutoDefault(True)
        self.closeButton.setFlat(False)
        self.minimizeButton = QPushButton(self.mainFrame)
        self.minimizeButton.setObjectName(u"minimizeButton")
        self.minimizeButton.setGeometry(QRect(990, 11, 49, 49))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush2 = QBrush(QColor(66, 132, 198, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush2)
        # if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush)
        # endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        # if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush)
        # endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        # if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush)
        # endif
        self.minimizeButton.setPalette(palette1)
        font12 = QFont()
        font12.setPointSize(45)
        font12.setBold(True)
        self.minimizeButton.setFont(font12)
        self.minimizeButton.setStyleSheet(style_sheet.minimizeButtonSS)
        icon6 = QIcon()
        icon6.addFile(u":/One/minus.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.minimizeButton.setIcon(icon6)
        self.minimizeButton.setIconSize(QSize(43, 43))
        self.minimizeButton.setAutoDefault(True)
        self.minimizeButton.setFlat(False)
        self.outputFolderLabel = QLabel(self.mainFrame)
        self.outputFolderLabel.setObjectName(u"outputFolderLabel")
        self.outputFolderLabel.setGeometry(QRect(35, 156, 251, 21))
        self.outputFolderLabel.setStyleSheet(style_sheet.outputFolderLabelSS)
        self.titleLabel.raise_()
        self.setOutputPathButton = QPushButton(self.mainFrame)
        self.setOutputPathButton.setObjectName(u"setOutputPathButton")
        self.setOutputPathButton.setEnabled(True)
        self.setOutputPathButton.setGeometry(QRect(377, 189, 41, 41))
        self.setOutputPathButton.setStyleSheet(style_sheet.setOutputPathButtonSS)
        icon4 = QIcon()
        icon4.addFile(u":/One/\u2014Pngtree\u2014vector folder icon_4139917.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.setOutputPathButton.setIcon(icon4)
        self.setOutputPathButton.setIconSize(QSize(35, 40))
        self.outputPathLineEdit = QLineEdit(self.mainFrame)
        self.outputPathLineEdit.setObjectName(u"outputPathLineEdit")
        self.outputPathLineEdit.setGeometry(QRect(22, 183, 341, 53))
        self.outputPathLineEdit.setStyleSheet(style_sheet.outputPathLineEditSS)
        self.outputPathLineEdit.setReadOnly(False)
        self.helpButton = QPushButton(self.mainFrame)
        self.helpButton.setObjectName(u"helpButton")
        self.helpButton.setGeometry(QRect(930, 11, 49, 49))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush3 = QBrush(QColor(85, 170, 127, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush3)
        # if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush)
        # endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        # if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush)
        # endif
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        # if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush)
        # endif
        self.helpButton.setPalette(palette2)
        font13 = QFont()
        font13.setPointSize(30)
        font13.setBold(True)
        self.helpButton.setFont(font13)
        self.helpButton.setToolTipDuration(5)
        self.helpButton.setStyleSheet(style_sheet.helpButtonSS)
        icon5 = QIcon()
        icon5.addFile(u":/One/help.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.helpButton.setIcon(icon5)
        self.helpButton.setIconSize(QSize(43, 43))
        self.helpButton.setAutoDefault(True)
        self.helpButton.setFlat(False)
        self.signLabel = QLabel(self.mainFrame)
        self.signLabel.setObjectName(u"signLabel")
        self.signLabel.setGeometry(QRect(826, 750, 281, 21))
        self.signLabel.setStyleSheet(style_sheet.signLabelSS)
        self.signLoveLabel = QLabel(self.mainFrame)
        self.signLoveLabel.setObjectName(u"signLoveLabel")
        self.signLoveLabel.setGeometry(QRect(916, 753, 21, 16))
        self.signLoveLabel.setStyleSheet(style_sheet.signLovelabelSS)
        self.titleLabel.raise_()
        self.selectVideoButton.raise_()
        self.infoFrame.raise_()
        self.convertFrame.raise_()
        self.closeButton.raise_()
        self.minimizeButton.raise_()
        self.setOutputPathButton.raise_()
        self.outputPathLineEdit.raise_()
        self.helpButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.resolutionComboBox.setCurrentIndex(0)

        QMetaObject.connectSlotsByName(MainWindow)

    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"UDEO", None))
        # if QT_CONFIG(tooltip)
        self.selectVideoButton.setToolTip("")
        # endif // QT_CONFIG(tooltip)
        # if QT_CONFIG(statustip)
        self.selectVideoButton.setStatusTip("")
        # endif // QT_CONFIG(statustip)
        self.selectVideoButton.setText(QCoreApplication.translate("MainWindow", u"+ Select Video", None))
        self.infothumbnaiLabel.setText("")
        self.infoplayVideoButton.setText("")
        self.infoNameLabel2.setText(QCoreApplication.translate("MainWindow", u"NA", None))
        self.infoNameLabel.setText(QCoreApplication.translate("MainWindow", u"Name :", None))
        self.infoLenghLabel2.setText(QCoreApplication.translate("MainWindow", u"NA", None))
        self.infoLenghLabel.setText(QCoreApplication.translate("MainWindow", u"Length :", None))
        self.infoBitrateLabel2.setText(QCoreApplication.translate("MainWindow", u"NA", None))
        self.infoBitrateLabel.setText(QCoreApplication.translate("MainWindow", u"Bitrate :", None))
        self.infoFpsLabel2.setText(QCoreApplication.translate("MainWindow", u"NA", None))
        self.infoFpsLabel.setText(QCoreApplication.translate("MainWindow", u"FPS :", None))
        self.infoResolutionLabel2.setText(QCoreApplication.translate("MainWindow", u"NA", None))
        self.infoResolutionLabel.setText(QCoreApplication.translate("MainWindow", u" Resolution :", None))
        self.videoInformationLabel.setText(QCoreApplication.translate("MainWindow", u"Video Information", None))
        self.infoSizeLabel2.setText(QCoreApplication.translate("MainWindow", u"NA", None))
        self.infoSizeLabel.setText(QCoreApplication.translate("MainWindow", u"Size :", None))
        self.mp4RadioButton.setText("")
        self.aviRadioButton.setText("")
        self.wmvRadioButton.setText("")
        self.outputFormatLabel.setText(QCoreApplication.translate("MainWindow", u"Output Formats", None))
        self.bitrateReductionLabel.setText(QCoreApplication.translate("MainWindow", u"Bitrate Reduction", None))
        self.fpsLabel.setText(QCoreApplication.translate("MainWindow", u"Frame Rate", None))
        self.resolutionLabel.setText(QCoreApplication.translate("MainWindow", u"Resolution ", None))
        self.outputSettingsLabel.setText(QCoreApplication.translate("MainWindow", u"Output Settings", None))
        self.provideSizeLineEdit.setText("")
        self.provideSizeLineEdit.setPlaceholderText(
            QCoreApplication.translate("MainWindow", u"Provide size in MB", None))
        self.targetSizeLabel.setText(QCoreApplication.translate("MainWindow", u"Target Size (MB)", None))
        self.keepAudioCheckBox.setText(QCoreApplication.translate("MainWindow", u" Keep Audio", None))
        self.fpsSpinBox.setPrefix("")
        self.bitrateReductionSpinBox.setPrefix("")
        self.bitrateReductionPercentLabel.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.resolutionComboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"                 Unset", None))
        self.resolutionComboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"              1920 x 1080", None))
        self.resolutionComboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"              1280 x 720", None))
        self.resolutionComboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"               640 x 480", None))

        self.trimVideoButton.setText(QCoreApplication.translate("MainWindow", u"Set Trim Interval", None))
        self.startTimeLabel.setText(QCoreApplication.translate("MainWindow", u"       Start Time ", None))
        self.endTimeLabel.setText(QCoreApplication.translate("MainWindow", u"       End Time ", None))
        self.startTimeLineEdit.setText("00:00:00")
        # self.startTimeLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.endTimeLineEdit.setText("00:00:00")
        # self.endTimeLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"00:00:00", None))
        self.trimSettingsLabel.setText(QCoreApplication.translate("MainWindow", u"Trim Settings", None))
        # if QT_CONFIG(tooltip)
        self.convertVideoButton.setToolTip("")
        # endif // QT_CONFIG(tooltip)
        self.convertVideoButton.setText(QCoreApplication.translate("MainWindow", u"Convert", None))
        self.conversionSettingsLabel.setText(QCoreApplication.translate("MainWindow", u"Conversion Settings", None))
        # if QT_CONFIG(tooltip)
        self.loadConfigButton.setToolTip("")
        # endif // QT_CONFIG(tooltip)
        self.loadConfigButton.setText(QCoreApplication.translate("MainWindow", u"Load Config", None))
        # if QT_CONFIG(tooltip)
        self.saveConfigButton.setToolTip("")
        # endif // QT_CONFIG(tooltip)
        self.saveConfigButton.setText(QCoreApplication.translate("MainWindow", u"Save Config", None))
        self.titleLabel.setText(
            QCoreApplication.translate("MainWindow", u"<html><head/><body><p>UDEO</p></body></html>", None))
        # self.closeButton.setText(QCoreApplication.translate("MainWindow", u"X", None))
        # self.minimizeButton.setText(QCoreApplication.translate("MainWindow", u"-", None))
        # if QT_CONFIG(tooltip)
        self.setOutputPathButton.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:11pt; color:#ffffff;\">Select folder to store converted video</span></p></body></html>", None))
        # endif // QT_CONFIG(tooltip)
        self.setOutputPathButton.setText("")
        self.outputPathLineEdit.setText("")
        # if QT_CONFIG(tooltip)
        self.helpButton.setToolTip(
            QCoreApplication.translate("MainWindow", u"<html><head/><body><p><br/></p></body></html>", None))
        # endif // QT_CONFIG(tooltip)
        # self.helpButton.setText(QCoreApplication.translate("MainWindow", u"?", None))
        self.outputFolderLabel.setText(QCoreApplication.translate("MainWindow", u"Set Output Folder", None))
        self.signLabel.setText(QCoreApplication.translate("MainWindow", u"Made With     In Ubisoft Pune", None))
        self.signLoveLabel.setText(QCoreApplication.translate("MainWindow", u"\u2665", None))
    # retranslateUi
